UZ_Web/Areas/Admin/Controllers/BlackListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UZ.BLL.Infrastructure.UZRequestModule;
using UZ.BLL.Interfaces;
using UZ.BLL.Models;
using UZ.Web.Controllers;
using UZ.Web.Models;

namespace UZ.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class BlackListController : BaseController
    {
        protected IDBService _dBService;


        public BlackListController(IUZRequestService _UZRequestService, IDBService dBService)
            : base(_UZRequestService)
        {
            _dBService = dBService;
        }

        [Route("admin/blacklist/")]
        public IActionResult Index()
        {
            var model = _dBService.BlackListService.Storage.OrderBy(blockedItem => blockedItem.Id);

            return View(model);
        }

        [HttpGet("admin/blacklist/create")]
        public IActionResult Create()
        {
            BlockedTrainDTO model = new BlockedTrainDTO();
            return View(model);
        }

        [HttpPost("admin/blacklist/create")]
        public async Task<IActionResult> Create(BlockedTrainDTO model)
        {
            if (ModelState.IsValid)
            {
                model.BlockedDate = DateTime.Now;
                var resultId = await _dBService.BlackListService.AddAsync(model);
                if (resultId != 0)
                {
                    TempData["SuccessAdd"] = true;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("TrainId", "Не удалось добавить поезд в черный список. Пожалуйста, повторите попытку позже.");
                    return View(model);
                }
            }
            
            return View(model);
        }

        [HttpDelete("admin/blacklist/remove")]
        public async Task<IActionResult> RemoveItem(int id)
        {
            bool result = false;

            result = await _dBService.BlackListService.RemoveAsync(id);

            NotificationViewModel notificationModel = new NotificationViewModel(result, "Отлично!", "Элемент успешно удален из ЧС.",
                "Упс!", "При удалении возникли ошибки.");

            return PartialView("_Notification", notificationModel);
        }

    }
}

UZ_Web/Areas/Admin/Views/BlackList/Create.cshtml
@using UZ.BLL.Models
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Добавить поезд в черный список";
}

@model BlockedTrainDTO
<link rel="stylesheet" href="~/css/edit.css" asp-append-version="true" />

<h1>@ViewData["Title"]</h1>
@await Html.PartialAsync("_BlackListItemForm",Model)

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

UZ_Web/Areas/Admin/Views/BlackList/Edit.cshtml
@using UZ.BLL.Models
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Редактирование ЧС";
}

@model BlockedTrainDTO
<link rel="stylesheet" href="~/css/edit.css" asp-append-version="true" />

<h1>@ViewData["Title"]</h1>
@await Html.PartialAsync("_BlackListItemForm", Model)

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

UZ_Web/Areas/Admin/Views/BlackList/Index.cshtml
@using UZ.BLL.Models
@using UZ.Web.Areas.Models
@using UZ.DAL.Models
@model IEnumerable<BlockedTrain>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Заблокированные поезда";
}

@section Styles{
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/MvcGrid/css/mvc-grid.css">
    <link rel="stylesheet" href="~/css/grid.css" asp-append-version="true">
    <link rel="stylesheet" href="~/lib/jquery-ui/css/jquery-ui.css">
}
@Html.Partial("~/Areas/Admin/Views/Shared/_AdminMenuHeader.cshtml", AdminMenuActiveType.BlackList)

<h1>@ViewData["Title"]</h1>
<br />
@if (TempData["SuccessAdd"] != null)
{
    <div id="Notifications" class="show">
        @await Html.PartialAsync("_Notification", new NotificationViewModel(true,"Отлично!","Новый элемент был добавлен!"))
    </div>
    <br />
}
else
{
    <div id="Notifications"></div>

}
<a asp-action="Create" asp-controller="BlackList" class="btn btn-secondary">Добавить</a>
<br />
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id).Titled("Id");
        columns.Add(model => model.TrainId).Titled("Поезд");
        columns.Add(model => model.BlockedDate).Titled("Дата блокировки").Formatted("{0: yyyy-MM-dd hh-mm-ss}");
        columns.Add(model => Html.Raw($"<div class='action-block'><div class='loader'><a href='#' class='btn btn-danger remove-item' id='blocked-remove={model.Id}' data-item='blocked' data-id='{ model.Id}'>Удалить</a></div></div>")).Titled("Действия").Encoded(false);
    })
    .Empty("Результатов не найдено")
    .Filterable()
    .Sortable()
    .Pageable()
    .Css("css-classes") // Overwrites all classes with the new ones
    .AppendCss("table-hover")
)

@section Scripts{
    <script src="~/lib/MvcGrid/js/mvc-grid.js"></script>
    <script src="~/lib/MvcGrid/js/localization.js"></script>
    <script src="~/lib/jquery-ui/js/jquery-ui.js"></script>
    <script src="~/js/custom-grid-filters.js" asp-append-version="true"></script>
    <script src="~/js/remove.js" asp-append-version="true"></script>
}

UZ_Web/Areas/Admin/Views/BlackList/_BlackListItemForm.cshtml
@model UZ.BLL.Models.BlockedTrainDTO
<form id="SaveBlockedTrain" method="post">
    <div class="hidden-block">
        <input asp-for="Id" type="hidden"/>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="TrainId"></label>
                <input asp-for="TrainId" class="form-control" />
                <span asp-validation-for="TrainId" class="text-danger"></span>
            </div>
            <div class="buttons-block">
                <button type="submit" class="btn btn-success">Сохранить</button>
            </div>
        </div>
    </div>
</form>