UZ_Web/Models/NotificationViewModel.cs
using System;

namespace UZ.Web.Models
{
    public class NotificationViewModel
    {
        public bool Success { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }  
        
        public NotificationViewModel(bool success, string title, string description)
        {
            Success = success;
            Title = title;
            Description = description;
        }

        public NotificationViewModel(bool success, string successTitle, string successDescription, string errorTitle, string errorDescription)
        {
            Success = success;
            if (success)
            {
                Title = successTitle;
                Description = successDescription;
            }
            else
            {
                Title = errorTitle;
                Description = errorDescription;
            }
            
        }

    }
}

UZ_Web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UZ.BLL.Infrastructure.UZRequestModule;
using UZ.BLL.Models;
using UZ.BLL.Utils;

namespace UZ.Web.Controllers
{
    [Route("cart")]
    public class CartController : BaseController
    {
        public CartController(IUZRequestService _uzService)
            : base(_uzService)
        {

        }

        [Route("add")]
        public IActionResult Index()
        {
            TicketDTO ticket = new TicketDTO()
            {
                Ord = 0,
                From = 2210670,
                To = 2204001,
                Train = "082П",
                //Date = "2018-09-07",
                WagonNumber = 6,
                WagonClass = "В",
                WagonType = "П",
                WagonRailway = 43,
                Charline = "Б",
                FirstName = "Геннадий",
                LastName = "Сараула",
                Bedding = 1,
                Services = new string[] {"Н"},
                Child = "",
                Student = "",
                Reserve = 0,
                PlaceNumber = 10
            };

            TicketDTO secondTicket = new TicketDTO()
            {
                Ord = 0,
                From = 2204001,
                To = 2208001,
                Train = "059О",
                //Date = "2018-08-24",
                WagonNumber = 9,
                WagonClass = "Б",
                WagonType = "П",
                WagonRailway = 40,
                Charline = "А",
                FirstName = "Татьяна",
                LastName = "Остапчук",
                Bedding = 1,
                Services = new string[] { "Н", "М" },
                Child = "",
                Student = "",
                Reserve = 0,
                PlaceNumber = 47
            };

            OrderDto order = new OrderDto(new List<TicketDTO>() { ticket });

            TicketResponse result = UZRequestService.AddTicketToCart(order, out string sessionId);
            string content = "";
            if (result != null && result.Error == 0)
            {
                //string cartHtml = UZRequestService.GetCart(sessionId);
                //List<string> reserveIds = StringUtils.GetReserveIdFromCartHtml(cartHtml);

                //string revokeResult = UZRequestService.RevokeTicketFromCart(sessionId, reserveIds.ToArray());

            }
            else if(result != null && result.Captcha == 1)
            {
                byte[] img = UZRequestService.GetTicketCaptchaImage(sessionId);
                return File(img, "image/gif");
            }


            return Content(content);
        }
    }
}

UZ_Web/Views/Shared/_Layout.cshtml
@{
    string controllerName = ViewContext.RouteData.Values["controller"].ToString();
    string actionName = ViewContext.RouteData.Values["action"].ToString();
    string areaName = ViewContext.RouteData.Values["area"]?.ToString() ?? "";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UZ.Web</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/common.min.css" asp-append-version="true" />
        @*<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">*@
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/common.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white @(areaName == "Admin" ? "admin-nav":"user-nav")">
            <div class="container">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Билеты Онлайн</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav mr-auto">
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Главная</a></li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("admin"))
                            {
                                <li class="nav-item"><a asp-area="Admin" asp-controller="TrainSearch" asp-action="Index" class="nav-link">Администрирование</a></li>
                            }
                            <li class="nav-item"><a asp-area="" asp-controller="Train" asp-action="UserSearches" class="nav-link">Мои запросы</a></li>
                        }
                        @*<li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="About" class="nav-link">О нас</a></li>
                            <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Contact" class="nav-link">Контакты</a></li>*@
                        @*<li class="nav-item"><a asp-area="" asp-controller="Train" asp-action="Index" class="nav-link">Поиск ж/д билетов</a></li>*@
                        @*<li class="nav-item"><a asp-area="" asp-controller="Cart" asp-action="Index" class="nav-link">Cart</a></li>*@

                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="main-container @(areaName == "Admin" ? "admin-main":"user-main")">
        <div class="container body-content">
            @RenderBody()
        </div>
        @if (controllerName == "Home" && actionName == "Index")
        {
            <div class="img-block">
                <img src="~/images/train_3.jpg" alt="Поезд" />
            </div>

        }
    </div>
    <footer>
        <div class="footer-wrp">
            <div class="container text-center">
                <p>&copy; 2018 - UZ-Web</p>
            </div>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

UZ_Web/Views/Shared/_Notification.cshtml
@model NotificationViewModel
<div class="alert alert-@(Model.Success ? "success" : "danger") alert-dismissible fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>@Model.Title</strong> @Model.Description
</div>